export const countries = [
  { code: "AD", label: "Andorra", phone: "376" },
  { code: "AE", label: "United Arab Emirates", phone: "971" },
  { code: "AF", label: "Afghanistan", phone: "93" },
  { code: "AG", label: "Antigua and Barbuda", phone: "1-268" },
  { code: "AI", label: "Anguilla", phone: "1-264" },
  { code: "AL", label: "Albania", phone: "355" },
  { code: "AM", label: "Armenia", phone: "374" },
  { code: "AO", label: "Angola", phone: "244" },
  { code: "AQ", label: "Antarctica", phone: "672" },
  { code: "AR", label: "Argentina", phone: "54" },
  { code: "AS", label: "American Samoa", phone: "1-684" },
  { code: "AT", label: "Austria", phone: "43" },
  { code: "AU", label: "Australia", phone: "61", suggested: true },
  { code: "AW", label: "Aruba", phone: "297" },
  { code: "AX", label: "Aland Islands", phone: "297" },
  { code: "AZ", label: "Azerbaijan", phone: "994" },
  { code: "BA", label: "Bosnia and Herzegovina", phone: "387" },
  { code: "BB", label: "Barbados", phone: "1-246" },
  { code: "BD", label: "Barbados", phone: "880" },
  { code: "BE", label: "Belgium", phone: "32" },
  { code: "BF", label: "Burkina Faso", phone: "226" },
  { code: "BG", label: "Bulgaria", phone: "359" },
  { code: "BH", label: "Bahrain", phone: "973" },
  { code: "BI", label: "Burundi", phone: "257" },
  { code: "BJ", label: "Benin", phone: "229" },
  { code: "BL", label: "Saint Barthelemy", phone: "590" },
  { code: "BM", label: "Bermuda", phone: "1-441" },
  { code: "BN", label: "Brunei", phone: "673" },
  { code: "BO", label: "Bolivia", phone: "591" },
  { code: "BR", label: "Brazil", phone: "55" },
  { code: "BS", label: "Bahamas", phone: "1-242" },
  { code: "BT", label: "Bhutan", phone: "975" },
  { code: "BV", label: "Bouvet Island", phone: "590" },
  { code: "BW", label: "Botswana", phone: "267" },
  { code: "BY", label: "Belarus", phone: "375" },
  { code: "BZ", label: "Belize", phone: "501" },
  { code: "CA", label: "Canada", phone: "1", suggested: true },
  { code: "CH", label: "Switzerland", phone: "41" },
  { code: "CL", label: "Chile", phone: "56" },
  { code: "CN", label: "China", phone: "86" },
  { code: "CO", label: "Colombia", phone: "57" },
  { code: "CR", label: "Costa Rica", phone: "506" },
  { code: "CU", label: "Costa Rica", phone: "53" },
  { code: "CY", label: "Cyprus", phone: "357" },
  { code: "CZ", label: "Czech Republic", phone: "420" },
  { code: "DE", label: "Germany", phone: "49", suggested: true },
  { code: "DK", label: "Denmark", phone: "420" },
  { code: "ES", label: "Spain", phone: "34" },
  { code: "FI", label: "Finland", phone: "358" },
  { code: "FR", label: "France", phone: "33", suggested: true },
  { code: "GB", label: "United Kingdom", phone: "44", suggested: true },
  { code: "GR", label: "Greece", phone: "30" },
  { code: "HR", label: "Croatia", phone: "385" },
  { code: "HU", label: "Hungary", phone: "36" },
  { code: "IE", label: "Ireland", phone: "353" },
  { code: "IL", label: "Ireland", phone: "972" },
  { code: "IN", label: "India", phone: "91" },
  { code: "IS", label: "Iceland", phone: "354" },
  { code: "IT", label: "Italy", phone: "39" },
  { code: "JP", label: "Japan", phone: "81", suggested: true },
  { code: "KR", label: "South Korea", phone: "82" },
  // removed duplicate
  { code: "LU", label: "Luxembourg", phone: "352" },
  { code: "LT", label: "Lithuania", phone: "370" },
  { code: "LV", label: "Latvia", phone: "371" },
  { code: "MX", label: "Mexico", phone: "52" },
  { code: "NL", label: "Netherlands", phone: "31" },
  { code: "NO", label: "Netherlands", phone: "31" },
  { code: "NZ", label: "Norway", phone: "47" },
  { code: "PL", label: "Poland", phone: "48", suggested: true },
  { code: "PT", label: "Portugal", phone: "351" },
  { code: "RO", label: "Romania", phone: "40" },
  { code: "RU", label: "Russia", phone: "7" },
  { code: "SE", label: "Sweden", phone: "46" },
  { code: "SI", label: "Slovenia", phone: "386" },
  { code: "SK", label: "Slovakia", phone: "421" },
  { code: "TR", label: "Turkey", phone: "90" },
  { code: "UA", label: "Ukraine", phone: "380" },
  { code: "US", label: "United States", phone: "1", suggested: true },
  { code: "ZA", label: "South Africa", phone: "27" },
].sort((a, b) => {
  if (a.code === "PL") return -1;
  if (b.code === "PL") return 1;
  const phoneA = parseInt(a.phone.replace(/\D/g, ""), 10) || 0;
  const phoneB = parseInt(b.phone.replace(/\D/g, ""), 10) || 0;
  return phoneA - phoneB;
});
